### ISSUE TITLE
请问国密双证书的ingress secert格式是怎样的？

### ISSUE THREAD

**Issue by Asutorufa** [alibaba/tengine#1981]
国密需要双证书，文档中只有单证书的例子？双证书的格式是怎样的？还是直接把两个证书和密钥叠加到一个pem文件中？

**Comment by IYism** [comment]
# GMSSL sign
    ssl_sign_certificate /etc/nginx/ssl/SS.cert.pem;
    ssl_sign_certificate_key /etc/nginx/ssl/SS.key.pem;

    # GMSSL enc
    ssl_enc_certificate /etc/nginx/ssl/SE.cert.pem;
    ssl_enc_certificate_key /etc/nginx/ssl/SE.key.pem;

**Comment by whbwyj** [comment]
#国密签名证书
  ssl_sign_certificate            sign.pem;
  ssl_sign_certificate_key      sign.key;

  #国密加密证书
  ssl_enc_certificate             enc.pem;
  ssl_enc_certificate_key      enc.key;

**Comment by Asutorufa** [comment]
> #国密签名证书 ssl_sign_certificate sign.pem; ssl_sign_certificate_key sign.key;
> 
> #国密加密证书 ssl_enc_certificate enc.pem; ssl_enc_certificate_key enc.key;

请问是这样吗？ @whbwyj 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: testsecret-tls
  namespace: default
data:
  sign.pem: base64 encoded cert
  sign.key: base64 encoded key
  enc.pem: base64 encoded cert
  enc.key: base64 encoded key
type: kubernetes.io/tls
```
